# Generated by Django 5.0.1 on 2024-02-05 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DER",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "der_type",
                    models.CharField(
                        choices=[
                            ("solar", "Solar Panel"),
                            ("wind", "Wind Turbine"),
                            ("battery", "Battery Storage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("location", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="EnergyProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("production", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "der",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vpp.der"
                    ),
                ),
            ],
        ),
    ]
